In [1]:
import pandas as pd
import os

# Configuration for limited RAM/Disk environment
HOSP = '../data_samples/hosp/'
ICU = '../data_samples/icu/'
NOTES = '../data_samples/note/'  # Adjust if your notes are elsewhere

In [2]:
os.listdir('../data_samples')

['note', 'hosp', 'icu', 'mimic-iv-bhc.csv']

## Pillars Formatting

In [3]:
def load_discharges(subject_ids=None):
    return filtered_read_csv(NOTES + 'discharge.csv', subject_ids)

def filtered_read_csv(file_path, subject_ids, usecols=None, **kwargs):
    """
    Helper to read large compressed CSVs in chunks and filter by subject_id.
    Uses 'usecols' to minimize memory footprint.
    """
    if usecols is not None and 'subject_id' not in usecols:
        usecols.append('subject_id')

    chunk_list = []
    try:
        for chunk in pd.read_csv(file_path, chunksize=250_000, usecols=usecols, engine='c', **kwargs):
            if subject_ids is not None:
                filtered_chunk = chunk[chunk['subject_id'].isin(subject_ids)]
            else:
                filtered_chunk = chunk
            
            if not filtered_chunk.empty:
                chunk_list.append(filtered_chunk)
    except FileNotFoundError:
        print(f"Warning: File not found at {file_path}")
        return pd.DataFrame()
    
    if not chunk_list:
        return pd.DataFrame(columns=usecols if usecols else [])

    df = pd.concat(chunk_list, ignore_index=True)
    df.columns = df.columns.str.lower()
    return df

def load_identity_pillar(subject_ids):
    admissions_cols = ['subject_id', 'hadm_id', 'admittime', 'race', 'admission_type', 'admission_location', 'insurance', 'marital_status']
    patients_cols = ['subject_id', 'gender', 'anchor_age', 'anchor_year', 'dod']
    omr_cols = ['subject_id', 'chartdate', 'result_name', 'result_value']

    admissions = filtered_read_csv(HOSP + 'admissions.csv', subject_ids, usecols=admissions_cols)
    patients = filtered_read_csv(HOSP + 'patients.csv', subject_ids, usecols=patients_cols)
    omr = filtered_read_csv(HOSP + 'omr.csv', subject_ids, usecols=omr_cols)

    if admissions.empty:
        return pd.DataFrame(columns=admissions_cols + ['timestamp', 'age_at_admission'])

    # Standardize Patients
    if patients.empty:
        patients = pd.DataFrame(columns=patients_cols)
        patients[['anchor_age', 'anchor_year']] = 0
    else:
        patients['anchor_year'] = pd.to_numeric(patients['anchor_year'], errors='coerce').fillna(0).astype(int)

    admissions['admittime'] = pd.to_datetime(admissions['admittime'])
    
    identity_df = admissions.merge(
        patients[['subject_id', 'gender', 'anchor_age', 'anchor_year', 'dod']], 
        on='subject_id', how='left'
    )

    identity_df['admission_year'] = identity_df['admittime'].dt.year
    # Fallback to admission_year if anchor_year is missing to avoid NaN age
    identity_df['age_at_admission'] = (identity_df['anchor_age'].fillna(0) + 
                                       (identity_df['admission_year'] - identity_df['anchor_year'].fillna(identity_df['admission_year'])))

    relevant_omr_names = ['Weight (Lbs)', 'Height (Inches)', 'BMI (kg/m2)', 'Blood Pressure']
    
    # Ensure OMR columns exist for pivot check
    if omr.empty:
        omr = pd.DataFrame(columns=omr_cols)

    baseline_omr = omr[omr['result_name'].isin(relevant_omr_names)].copy()
    
    if not baseline_omr.empty:
        baseline_omr = baseline_omr.sort_values('chartdate').groupby(['subject_id', 'result_name']).head(1)
        omr_pivot = baseline_omr.pivot(index='subject_id', columns='result_name', values='result_value').reset_index()
        identity_df = identity_df.merge(omr_pivot, on='subject_id', how='left')
    else:
        # Create the columns manually if no OMR data exists
        for col in relevant_omr_names:
            identity_df[col] = "Not Recorded"
    
    identity_df['timestamp'] = identity_df['admittime']
    
    identity_df = identity_df.rename(columns={
        'Weight (Lbs)': 'weight_baseline', 'Height (Inches)': 'height_baseline',
        'BMI (kg/m2)': 'bmi_baseline', 'Blood Pressure': 'blood_pressure_baseline',
    })

    relevant_cols = [
        'subject_id', 'hadm_id', 'timestamp', 'age_at_admission', 'gender', 'race',
        'admission_type', 'admission_location', 'insurance', 'marital_status',
        'weight_baseline', 'height_baseline', 'bmi_baseline', 'blood_pressure_baseline', 'dod'
    ]
    return identity_df[[c for c in relevant_cols if c in identity_df.columns]]


def load_logistics_pillar(subject_ids):
    # 1. Load data
    transfers = filtered_read_csv(HOSP + 'transfers.csv', subject_ids, usecols=['subject_id', 'hadm_id', 'careunit', 'intime', 'outtime', 'eventtype'])
    services = filtered_read_csv(HOSP + 'services.csv', subject_ids, usecols=['subject_id', 'hadm_id', 'curr_service', 'transfertime'])
    admissions = filtered_read_csv(HOSP + 'admissions.csv', subject_ids, usecols=['subject_id', 'hadm_id', 'admission_location', 'discharge_location'])

    # 2. Early Exit Guard: If no transfers, return empty with SUBJECT_ID
    if transfers.empty:
        return pd.DataFrame(columns=['subject_id', 'hadm_id', 'careunit', 'intime', 'outtime', 'eventtype', 'timestamp'])

    # 3. Convert timestamps
    transfers['intime'] = pd.to_datetime(transfers['intime'])
    transfers['outtime'] = pd.to_datetime(transfers['outtime'])
    services['transfertime'] = pd.to_datetime(services['transfertime'])
    
    # 4. Merge Admissions (Use both keys to prevent subject_id_x/y)
    logistics_df = transfers.dropna(subset=['hadm_id']).merge(
        admissions[['subject_id', 'hadm_id', 'admission_location', 'discharge_location']], 
        on=['subject_id', 'hadm_id'], 
        how='left'
    )

    # 5. Prepare for merge_asof
    # AsOf merge requires sorted keys and NO NaNs in the merge-on or by columns
    services = services.dropna(subset=['hadm_id', 'transfertime']).sort_values('transfertime')
    logistics_df = logistics_df.dropna(subset=['hadm_id', 'intime']).sort_values('intime')
    
    # Force types to match to avoid merge errors
    logistics_df['hadm_id'] = logistics_df['hadm_id'].astype('int64')
    services['hadm_id'] = services['hadm_id'].astype('int64')

    # 6. Perform the merge_asof
    if not services.empty:
        # Note: 'by' handles the grouping, so we match service to transfer by hadm_id
        logistics_df = pd.merge_asof(
            logistics_df, 
            services[['hadm_id', 'curr_service', 'transfertime']], 
            left_on='intime', 
            right_on='transfertime', 
            by='hadm_id', 
            direction='backward'
        )
    else:
        logistics_df['curr_service'] = pd.NA

    # 7. Final Cleanup
    logistics_df = logistics_df.dropna(subset=['careunit'])
    logistics_df['stay_duration_hours'] = (logistics_df['outtime'] - logistics_df['intime']).dt.total_seconds() / 3600
    logistics_df['timestamp'] = logistics_df['intime']
    
    # 8. EMERGENCY CHECK: If subject_id was lost, try to recover it from index
    if 'subject_id' not in logistics_df.columns:
        if logistics_df.index.name == 'subject_id':
            logistics_df = logistics_df.reset_index()
        else:
            # This shouldn't happen with the fix above, but let's be safe
            print("Warning: subject_id lost in logistics merge. Attempting recovery.")
            # If we lost it, we can't do much but return an empty DF with the column to stop the crash
            logistics_df['subject_id'] = pd.NA

    return logistics_df

def load_monitoring_pillar(subject_ids):
    d_items = pd.read_csv(ICU + 'd_items.csv')
    vitals_dict = d_items[['itemid', 'label', 'lownormalvalue', 'highnormalvalue']]

    # --- 1. Process Chartevents (ICU) ---
    icu_vitals_list = []
    icu_cols = ['subject_id', 'hadm_id', 'itemid', 'charttime', 'valuenum', 'valueuom']
    
    # Using your optimized chunk loop
    for chunk in pd.read_csv(ICU + 'chartevents.csv', chunksize=250_000, usecols=icu_cols):
        f_chunk = chunk[chunk['subject_id'].isin(subject_ids)]
        if not f_chunk.empty:
            icu_vitals_list.append(f_chunk)
    
    if icu_vitals_list:
        icu_vitals = pd.concat(icu_vitals_list, ignore_index=True)
        icu_vitals = icu_vitals.merge(vitals_dict, on='itemid', how='inner')
        if not icu_vitals.empty:
            icu_vitals['timestamp'] = pd.to_datetime(icu_vitals['charttime'])
            icu_vitals['source'] = 'ICU'
    else:
        # Guarantee columns even if empty
        icu_vitals = pd.DataFrame(columns=icu_cols + ['label', 'timestamp', 'source'])

    # --- 2. Process OMR (Ward) ---
    omr = filtered_read_csv(HOSP + 'omr.csv', subject_ids, usecols=['subject_id', 'chartdate', 'result_name', 'result_value'])
    admissions = filtered_read_csv(HOSP + 'admissions.csv', subject_ids, usecols=['subject_id', 'hadm_id', 'admittime', 'dischtime'])

    if not omr.empty:
        # Safe string filtering
        ward_vitals = omr[omr['result_name'].str.contains('Blood Pressure', na=False)].copy()
        
        if not ward_vitals.empty:
            ward_vitals['timestamp'] = pd.to_datetime(ward_vitals['chartdate'])
            # Merge on subject_id and handle multiple admissions safely
            ward_vitals = ward_vitals.merge(admissions, on='subject_id', how='left')
            
            # Ensure admission dates exist before masking
            ward_vitals = ward_vitals.dropna(subset=['admittime', 'dischtime'])
            
            if not ward_vitals.empty:
                mask = (ward_vitals['timestamp'] >= pd.to_datetime(ward_vitals['admittime']).dt.normalize()) & \
                       (ward_vitals['timestamp'] <= pd.to_datetime(ward_vitals['dischtime']).dt.normalize())
                ward_vitals = ward_vitals[mask].rename(columns={'result_name': 'label', 'result_value': 'valuenum'})
                ward_vitals['source'] = 'WARD'
            else:
                ward_vitals = pd.DataFrame(columns=icu_vitals.columns)
        else:
            ward_vitals = pd.DataFrame(columns=icu_vitals.columns)
    else:
        ward_vitals = pd.DataFrame(columns=icu_vitals.columns)

    # --- 3. Combine and Finalize ---
    # Combine everything. ignore_index helps avoid duplicate index issues.
    monitoring_df = pd.concat([icu_vitals, ward_vitals], axis=0, ignore_index=True)
    
    if monitoring_df.empty:
        return monitoring_df

    return monitoring_df.sort_values(['subject_id', 'timestamp'])

def load_investigations_pillar(subject_ids):
    # 1. Load Dictionary
    d_labitems = pd.read_csv(HOSP + 'd_labitems.csv')
    
    # Define a consistent schema for the "Investigations" pillar
    investigation_cols = [
        'subject_id', 'hadm_id', 'timestamp', 'type', 'label', 
        'valuenum', 'valueuom', 'flag', 'spec_type_desc', 
        'test_name', 'org_name', 'comments'
    ]

    # --- 2. Process Labs ---
    lab_cols = ['subject_id', 'hadm_id', 'itemid', 'charttime', 'valuenum', 'valueuom', 'flag']
    labs_df = filtered_read_csv(HOSP + 'labevents.csv', subject_ids, usecols=lab_cols)
    
    if not labs_df.empty:
        labs_df['timestamp'] = pd.to_datetime(labs_df['charttime'])
        labs_final = labs_df.merge(d_labitems[['itemid', 'label', 'fluid', 'category']], on='itemid', how='left')
        labs_final['type'] = 'LAB'
    else:
        labs_final = pd.DataFrame(columns=investigation_cols)

    # --- 3. Process Microbiology ---
    # Micro often doesn't have an itemid, it uses spec_type_desc and test_name
    micro_df = filtered_read_csv(HOSP + 'microbiologyevents.csv', subject_ids)
    
    if not micro_df.empty:
        micro_df['timestamp'] = pd.to_datetime(micro_df['charttime'])
        # Keep original columns for investigations_text logic
        micro_final = micro_df.copy()
        if 'spec_type_desc' in micro_final.columns:
            micro_final['label'] = micro_final['spec_type_desc']
        micro_final['type'] = 'MICRO'
    else:
        micro_final = pd.DataFrame(columns=investigation_cols)

    # --- 4. Combine and Clean ---
    # Concatenate while ensuring we don't lose unique columns from either source
    df = pd.concat([labs_final, micro_final], axis=0, ignore_index=True)
    
    if df.empty:
        return pd.DataFrame(columns=investigation_cols)

    # Convert hadm_id to Int64 (nullable integer) to handle potential NaNs safely
    if 'hadm_id' in df.columns:
        df['hadm_id'] = pd.to_numeric(df['hadm_id'], errors='coerce')
        # Optional: if you still want to drop labs not associated with a stay:
        df = df.dropna(subset=['hadm_id'])
        df['hadm_id'] = df['hadm_id'].astype('int64')

    return df.sort_values(['subject_id', 'timestamp'])

def load_interventions_pillar(subject_ids):
    # 1. ICU Bedside Procedures
    d_items = pd.read_csv(ICU + 'd_items.csv')
    icu_procs = filtered_read_csv(ICU + 'procedureevents.csv', subject_ids)
    
    # Initialize empty with columns to ensure concat safety
    required_cols = ['subject_id', 'hadm_id', 'timestamp', 'label', 'proc_type']
    
    if not icu_procs.empty:
        icu_procs['timestamp'] = pd.to_datetime(icu_procs['starttime'])
        icu_procs = icu_procs.merge(d_items[['itemid', 'label']], on='itemid', how='left')
        icu_procs['proc_type'] = 'ICU_BEDSIDE'
    else:
        icu_procs = pd.DataFrame(columns=required_cols)

    # 2. Billed Surgical Procedures (Hosp)
    d_icd_procs = pd.read_csv(HOSP + 'd_icd_procedures.csv')
    billed_procs = filtered_read_csv(HOSP + 'procedures_icd.csv', subject_ids)
    admissions = filtered_read_csv(HOSP + 'admissions.csv', subject_ids, usecols=['hadm_id', 'admittime', 'subject_id'])
    
    if not billed_procs.empty:
        billed_procs = billed_procs.merge(d_icd_procs, on=['icd_code', 'icd_version'], how='left')
        # FIX: Merge on both keys to avoid subject_id_x/y
        billed_procs = billed_procs.merge(admissions, on=['hadm_id', 'subject_id'], how='left')
        
        billed_procs['timestamp'] = pd.to_datetime(billed_procs['admittime'])
        billed_procs['proc_type'] = 'BILLED_SURGICAL'
        billed_procs = billed_procs.rename(columns={'long_title': 'label'})
    else:
        billed_procs = pd.DataFrame(columns=required_cols)

    # 3. Combine and Finalize
    # Check if both are empty after filtering
    if icu_procs.empty and billed_procs.empty:
        return pd.DataFrame(columns=required_cols)
    
    # concat handles the union of columns
    combined = pd.concat([icu_procs, billed_procs], axis=0, ignore_index=True)
    
    # Final cleanup: ensure no missing critical columns before sorting
    if 'subject_id' not in combined.columns or 'timestamp' not in combined.columns:
        return pd.DataFrame(columns=required_cols)

    return combined.sort_values(['subject_id', 'timestamp'])

def load_inputs_pillar(subject_ids):
    # 1. Setup Dictionaries and Schemas
    d_items = pd.read_csv(ICU + 'd_items.csv')
    
    # Define a shared schema so the final DataFrame is consistent
    shared_cols = [
        'subject_id', 'hadm_id', 'timestamp', 'label', 'amount', 
        'amountuom', 'rate', 'rateuom', 'route', 'input_type'
    ]

    # --- 2. Process ICU Inputs ---
    icu_cols = ['subject_id', 'hadm_id', 'itemid', 'starttime', 'amount', 'amountuom', 'rate', 'rateuom']
    icu_inputs = filtered_read_csv(ICU + 'inputevents.csv', subject_ids, usecols=icu_cols)
    
    if not icu_inputs.empty:
        icu_inputs['timestamp'] = pd.to_datetime(icu_inputs['starttime'])
        icu_inputs = icu_inputs.merge(d_items[['itemid', 'label']], on='itemid', how='left')
        icu_inputs['input_type'] = 'ICU_INPUT'
        # ICU inputs are usually IV
        if 'route' not in icu_inputs.columns:
            icu_inputs['route'] = 'IV'
    else:
        icu_inputs = pd.DataFrame(columns=shared_cols)

    # --- 3. Process Ward Prescriptions ---
    rx_cols = ['subject_id', 'hadm_id', 'starttime', 'drug', 'dose_val_rx', 'dose_unit_rx', 'route']
    ward_inputs = filtered_read_csv(HOSP + 'prescriptions.csv', subject_ids, usecols=rx_cols)
    
    if not ward_inputs.empty:
        ward_inputs['timestamp'] = pd.to_datetime(ward_inputs['starttime'])
        ward_inputs = ward_inputs.rename(columns={
            'drug': 'label', 
            'dose_val_rx': 'amount', 
            'dose_unit_rx': 'amountuom'
        })
        ward_inputs['input_type'] = 'WARD_PRESCRIPTION'
        # Ward data usually doesn't have 'rate'
        ward_inputs['rate'] = pd.NA
        ward_inputs['rateuom'] = pd.NA
    else:
        ward_inputs = pd.DataFrame(columns=shared_cols)

    # --- 4. Combine and Clean ---
    if icu_inputs.empty and ward_inputs.empty:
        return pd.DataFrame(columns=shared_cols)

    combined = pd.concat([icu_inputs, ward_inputs], axis=0, ignore_index=True)
    
    # Filter for valid columns and ensure hadm_id is int64
    combined = combined[[c for c in shared_cols if c in combined.columns]]
    combined = combined.dropna(subset=['subject_id', 'timestamp'])
    
    if not combined.empty and 'hadm_id' in combined.columns:
        combined['hadm_id'] = pd.to_numeric(combined['hadm_id'], errors='coerce').fillna(0).astype('int64')

    return combined.sort_values(['subject_id', 'timestamp'])

def load_conclusion_pillar(subject_ids):
    # 1. Load Dictionary (Using variable for consistency)
    d_diag = pd.read_csv(HOSP + 'd_icd_diagnoses.csv')
    
    diagnoses = filtered_read_csv(HOSP + 'diagnoses_icd.csv', subject_ids)
    admissions = filtered_read_csv(HOSP + 'admissions.csv', subject_ids, usecols=['hadm_id', 'dischtime', 'subject_id'])

    required_cols = ['subject_id', 'hadm_id', 'timestamp', 'diagnosis_label', 'seq_num', 'icd_code', 'icd_version']

    # 2. Safety Check: Early exit if no diagnoses found
    if diagnoses.empty:
        return pd.DataFrame(columns=required_cols)

    # 3. Data Cleaning (Crucial for the Merge)
    diagnoses['icd_code'] = diagnoses['icd_code'].astype(str).str.strip()
    d_diag['icd_code'] = d_diag['icd_code'].astype(str).str.strip()
    
    # Force icd_version to match types (usually int)
    diagnoses['icd_version'] = pd.to_numeric(diagnoses['icd_version'], errors='coerce')
    d_diag['icd_version'] = pd.to_numeric(d_diag['icd_version'], errors='coerce')

    # 4. Merging Logic
    # Left merge ensures we keep the diagnosis even if the dictionary is missing the label
    outcomes = diagnoses.merge(d_diag, on=['icd_code', 'icd_version'], how='left')
    outcomes = outcomes.merge(admissions, on=['hadm_id', 'subject_id'], how='left')
    
    # 5. Column Formatting
    outcomes['timestamp'] = pd.to_datetime(outcomes['dischtime'])
    outcomes = outcomes.rename(columns={'long_title': 'diagnosis_label'})
    
    # Fallback: If no long_title was found, use the code itself
    outcomes['diagnosis_label'] = outcomes['diagnosis_label'].fillna("ICD Code " + outcomes['icd_code'])
    
    # Final cleanup of identifiers
    if not outcomes.empty:
        outcomes['hadm_id'] = pd.to_numeric(outcomes['hadm_id'], errors='coerce').fillna(0).astype('int64')

    # Filter for valid required columns that exist
    final_cols = [c for c in required_cols if c in outcomes.columns]
    return outcomes[final_cols].sort_values(['subject_id', 'seq_num'])

## Text Construction

In [ ]:
def logistics_text(df) -> str:
    text = ""
    transfer_flag = False

    for row in df.itertuples():
        if row.eventtype == 'admit':
            text += f"The patient was formally admitted to {row.careunit} via {row.admission_location}. "
        
        elif row.eventtype == 'ED':
            text += f"The patient initially presented at the Emergency Department ({row.careunit}). "
            
        elif row.eventtype == 'transfer':
            if not transfer_flag:
                text += "\nInternal movements within the hospital included:"
                transfer_flag = True
            duration_str = f" for {int(row.stay_duration_hours)} hours" if hasattr(row, 'stay_duration_hours') else ""
            text += f"\n - Moved to {row.careunit}{duration_str}."
            
        elif row.eventtype == 'discharge':
            loc = getattr(row, 'discharge_location', 'Home')
            text += f"\nThe patient was discharged {loc} by the end of the day."
    return text

def monitoring_text(df) -> str:

    if df is None or df.empty:
        return ''

    # Sort chronologically (no dropping)
    df = df.sort_values('timestamp')

    lines = []

    for i in df.itertuples():
        label = getattr(i, 'label', 'Unknown')

        valuenum = getattr(i, 'valuenum', None)
        value = getattr(i, 'value', None)
        unit = getattr(i, 'valueuom', '')

        # Prefer numeric if available, else fallback to text
        if pd.notna(valuenum):
            unit_str = "" if pd.isna(unit) else str(unit)
            val_str = f"{valuenum}{unit_str}"
        elif pd.notna(value):
            val_str = str(value)
        else:
            val_str = "No value recorded"

        lines.append(f"- {label}: {val_str}")

    if not lines:
        return ""

    return "Vital Signs and Observations:\n" + "\n".join(lines)


def investigations_text(df) -> str:
    if df.empty:
        return ""
    
    # Sort everything chronologically
    if 'timestamp' in df.columns:
        df = df.sort_values('timestamp')

    sections = []

    # --- 1. LAB EVENTS (abnormal only, no grouping) ---
    labs = df[(df['type'] == 'LAB') & (df['flag'] == 'abnormal')]
    
    if not labs.empty:
        lab_lines = []

        for r in labs.itertuples():
            label = getattr(r, 'label', 'Unknown Lab')

            if pd.notna(getattr(r, 'valuenum', None)):
                val = r.valuenum
                unit = getattr(r, 'valueuom', '')
                unit_str = str(unit) if pd.notna(unit) else ""
                value_str = f"{val}{unit_str}"
            else:
                value_str = str(getattr(r, 'value', ''))

            lab_lines.append(f"- {label}: {value_str}")

        sections.append("Abnormal Lab Findings:\n" + "\n".join(lab_lines))

    # --- 2. MICROBIOLOGY (no grouping, no dedup) ---
    micro = df[df['type'] == 'MICRO']
    
    if not micro.empty:
        micro_lines = []

        for row in micro.itertuples():
            spec = getattr(row, 'label', 'Unknown Specimen')
            test = getattr(row, 'test_name', 'Unknown Test')

            if pd.notna(getattr(row, 'org_name', None)):
                result = f"Positive for {row.org_name}"
            elif pd.notna(getattr(row, 'comments', None)) and str(row.comments).strip() not in ["", "___"]:
                result = str(row.comments).split('.')[0].strip()
            else:
                result = "Pending/Negative"

            micro_lines.append(f"- {spec} ({test}): {result}")

        sections.append("Microbiology & Immunology:\n" + "\n".join(micro_lines))

    return "\n".join(sections)


def interventions_text(df) -> str:
    if df.empty:
        return ""

    # Ensure chronological order
    if 'timestamp' in df.columns:
        df = df.sort_values('timestamp')

    sections = []

    # --- 1. Billed / Surgical Procedures (no dedup, itemized) ---
    surgical = df[df['proc_type'] == 'BILLED_SURGICAL']
    if not surgical.empty:
        s_lines = []

        for row in surgical.itertuples():
            label = str(getattr(row, 'label', 'Unknown Procedure')).strip()
            s_lines.append(f"- {label}")

        sections.append("Major/Billed Procedures:\n" + "\n".join(s_lines))

    # --- 2. ICU Bedside Procedures (no dedup, itemized) ---
    bedside = df[df['proc_type'] == 'ICU_BEDSIDE']
    if not bedside.empty:
        b_lines = []

        for row in bedside.itertuples():
            label = str(getattr(row, 'label', 'Unknown Procedure')).strip()
            b_lines.append(f"- {label}")

        sections.append("ICU Bedside Interventions:\n" + "\n".join(b_lines))

    return "\n".join(sections)

def medication_text(df):
    if df is None or df.empty:
        return ""
    
    df = df.sort_values('timestamp').copy()
    
    admin_entries = []

    for row in df.itertuples():
        label = str(getattr(row, 'label', 'Unknown Medication'))
        route = str(getattr(row, 'route', 'unspecified route'))

        amount = getattr(row, 'amount', None)
        uom = getattr(row, 'amountuom', '')
        rate = getattr(row, 'rate', None)
        rate_uom = getattr(row, 'rateuom', '')

        dose_parts = []

        # Include amount if present
        if pd.notna(amount) and str(amount) != 'nan':
            dose_parts.append(f"{amount} {uom}".strip())

        # Include rate if present
        if pd.notna(rate) and str(rate) != 'nan':
            dose_parts.append(f"{rate} {rate_uom}".strip())

        # Build final dose string
        if dose_parts:
            dose_info = " at ".join(dose_parts) if len(dose_parts) > 1 else f"dose of {dose_parts[0]}"
        else:
            dose_info = "administered"

        admin_entries.append(f"{label} {dose_info} via {route}")

    if not admin_entries:
        return ""

    return "Medication Administration History:\n- " + "\n- ".join(admin_entries)


def conclusion_text(df):
    if df is None or df.empty:
        return ""

    diag_df = df.sort_values('seq_num')

    primary_row = diag_df.iloc[0]
    primary = f"ICD-{primary_row.icd_version} {primary_row.icd_code}"

    secondary = [
        f"ICD-{row.icd_version} {row.icd_code}"
        for row in diag_df.iloc[1:].itertuples()
    ]

    text_parts = [f"Primary Diagnosis: {primary}."]

    if secondary:
        text_parts.append(f"Secondary Conditions: {', '.join(secondary)}.")

    return "\n".join(text_parts)

def context_builder_v2(window_cuts):
    """
    Inputs: window_cuts -> dict of DataFrames (identity, logistics, monitoring, etc.)
    already sliced for one specific patient and one specific time window.
    Output: A single stitched string.
    """
    paragraphs = []

    # 1. Identity (The Intro)
    # We assume identity is passed in the dict; usually contains 1 row per admission
    if 'identity' in window_cuts and not window_cuts['identity'].empty:
        id_df = window_cuts['identity']
        row = id_df.iloc[0] # Take the most recent/relevant identity row
        paragraphs.append(
            f"Patient is a {row.age_at_admission} year old {row.gender} ({row.race}). "
            f"They were admitted via {row.admission_location} by {row.admission_type}. "
            f"Baseline patient data shows: \nweight {row.weight_baseline}, height {row.height_baseline}, bmi {row.bmi_baseline}, blood pressure {row.blood_pressure_baseline}"
        )

    # # # 2. Logistics (The Journey)
    if 'logistics' in window_cuts and not window_cuts['logistics'].empty:
        paragraphs.append(logistics_text(window_cuts['logistics']))
        

    # 3. Monitoring (The Vitals)
    if 'monitoring' in window_cuts and not window_cuts['monitoring'].empty:
        mon = window_cuts['monitoring'].sort_values('timestamp')
        paragraphs.append(monitoring_text(mon))
        

    # 4. Investigations (The Labs)
    if 'investigations' in window_cuts and not window_cuts['investigations'].empty:
        inv = window_cuts['investigations']
        paragraphs.append(investigations_text(inv))

    # 5. Inputs (The Meds) --> Exception
    if 'inputs' in window_cuts and not window_cuts['inputs'].empty:
        meds = window_cuts['inputs']
        paragraphs.append(medication_text(meds))

    # 6. Interventions (The Actions) --> Exception
    if 'interventions' in window_cuts and not window_cuts['interventions'].empty:
        procs = window_cuts['interventions']
        paragraphs.append(interventions_text(procs))

    # 7. Conclusion (The Diagnoses)
    if 'conclusion' in window_cuts and not window_cuts['conclusion'].empty:
        diag_para = conclusion_text(window_cuts['conclusion'])
        if diag_para:
            paragraphs.append(diag_para)

    # Stitch all paragraphs into one clean block
    return '\n'.join(paragraphs)

In [ ]:
def build_header(window_cuts):

    header_parts = []

    if 'identity' in window_cuts and not window_cuts['identity'].empty:
        id_df = window_cuts['identity']
        row = id_df.iloc[0]

        header_parts.append(
            f"Patient is a {row.age_at_admission} year old {row.gender} ({row.race}). "
            f"They were admitted via {row.admission_location} by {row.admission_type}. "
            f"Baseline patient data shows: "
            f"weight {row.weight_baseline}, height {row.height_baseline}, "
            f"bmi {row.bmi_baseline}, blood pressure {row.blood_pressure_baseline}."
        )

    return "\n".join(header_parts)

def build_day_block(window_cuts):

    paragraphs = []

    if 'logistics' in window_cuts and not window_cuts['logistics'].empty:
        paragraphs.append(logistics_text(window_cuts['logistics']))

    if 'monitoring' in window_cuts and not window_cuts['monitoring'].empty:
        mon = window_cuts['monitoring'].sort_values('timestamp')
        paragraphs.append(monitoring_text(mon))

    if 'investigations' in window_cuts and not window_cuts['investigations'].empty:
        paragraphs.append(investigations_text(window_cuts['investigations']))

    if 'inputs' in window_cuts and not window_cuts['inputs'].empty:
        paragraphs.append(medication_text(window_cuts['inputs']))

    if 'interventions' in window_cuts and not window_cuts['interventions'].empty:
        paragraphs.append(interventions_text(window_cuts['interventions']))

    return '\n'.join(paragraphs)


def build_footer(window_cuts):

    footer_parts = []

    footer_parts.append(
        "Hospital Course Summary:"
    )

    # =========================
    # 1. VITAL SIGNS SUMMARY
    # =========================
    mon = window_cuts.get('monitoring', pd.DataFrame())

    if mon is not None and not mon.empty:
        mon = mon.copy()
        mon = mon.sort_values('timestamp')

        # Only numeric values for aggregation
        mon_num = mon[pd.notna(mon.get('valuenum'))]

        if not mon_num.empty:
            summary_lines = []

            grouped = mon_num.groupby('label')['valuenum'].agg(['min', 'max', 'mean'])

            for label, row in grouped.iterrows():
                try:
                    min_v = round(row['min'], 2)
                    max_v = round(row['max'], 2)
                    avg_v = round(row['mean'], 2)

                    summary_lines.append(
                        f"- {label}: min {min_v}, max {max_v}, avg {avg_v}"
                    )
                except Exception:
                    continue

            if summary_lines:
                footer_parts.append(
                    "Vital Signs Summary:\n" + "\n".join(summary_lines)
                )

    # =========================
    # 2. MEDICATION SUMMARY
    # =========================
    meds = window_cuts.get('inputs', pd.DataFrame())

    if meds is not None and not meds.empty:
        meds = meds.copy()

        # Drop rows where label is missing or meaningless
        meds = meds[
            meds['label'].notna() & 
            (meds['label'].astype(str).str.strip().str.lower() != 'nan')
        ]

        if not meds.empty:
            # Use label directly (no need for fallback in your schema)
            meds['clean_label'] = meds['label'].astype(str)

            counts = meds['clean_label'].value_counts()

            med_lines = [
                f"- {drug}: {count} administrations"
                for drug, count in counts.items()
            ]

            if med_lines:
                footer_parts.append(
                    "Medication Summary:\n" + "\n".join(med_lines)
                )

    # =========================
    # 3. ABNORMAL LAB SUMMARY
    # =========================
    labs = window_cuts.get('investigations', pd.DataFrame())

    if labs is not None and not labs.empty:
        labs = labs.copy()

        abnormal = labs[
            (labs.get('type') == 'LAB') &
            (labs.get('flag') == 'abnormal')
        ]

        if not abnormal.empty:
            counts = abnormal['label'].value_counts()

            lab_lines = [
                f"- {lab}: {count} abnormal readings"
                for lab, count in counts.items()
            ]

            if lab_lines:
                footer_parts.append(
                    "Abnormal Lab Summary:\n" + "\n".join(lab_lines)
                )

    # =========================
    # 4. DIAGNOSES
    # =========================
    if 'conclusion' in window_cuts and not window_cuts['conclusion'].empty:
        diag_para = conclusion_text(window_cuts['conclusion'])
        if diag_para:
            footer_parts.append(diag_para)

    return "\n\n".join(footer_parts)


def context_builder_v3(window_cuts):

    sections = []

    # HEADER
    header = build_header(window_cuts)
    if header:
        sections.append("--- Patient Information ---")
        sections.append(header)

    # BODY (group by day)
    timestamps = []

    for df in window_cuts.values():
        if isinstance(df, pd.DataFrame) and 'timestamp' in df.columns:
            timestamps.extend(pd.to_datetime(df['timestamp']).dropna().tolist())

    if timestamps:
        start = min(timestamps)
        end = max(timestamps)

        day_range = pd.date_range(start.normalize(), end.normalize(), freq='D')
        sections.append("\n--- Hospital Course ---")

        for day_number, day_start in enumerate(day_range, start=1):

            day_end = day_start + pd.Timedelta(days=1)
            daily_cuts = {}
            for category, df in window_cuts.items():

                if 'timestamp' in df.columns:
                    mask = (df['timestamp'] >= day_start) & (df['timestamp'] < day_end)
                    daily_cuts[category] = df[mask]
                else:
                    daily_cuts[category] = df

            day_text = build_day_block(daily_cuts)

            if day_text.strip():
                sections.append(f"\nDay {day_number}")
                sections.append(day_text)

    # FOOTER
    footer = build_footer(window_cuts)
    if footer:
        sections.append("\n--- Conclusions ---")
        sections.append(footer)

    return "\n".join(sections)

In [6]:
def load_clinical_context(subject_ids):

    context = dict()

    context['identity'] = load_identity_pillar(subject_ids)
    print('identity pillar has been loaded')
    context['logistics'] = load_logistics_pillar(subject_ids)
    print('logistics pillar has been loaded')
    context['monitoring'] = load_monitoring_pillar(subject_ids)
    print('monitoring pillar has been loaded')
    context['investigations'] = load_investigations_pillar(subject_ids)
    print('investigations pillar has been loaded')
    context['interventions'] = load_interventions_pillar(subject_ids)
    print('interventions pillar has been loaded')
    context['inputs'] = load_inputs_pillar(subject_ids)
    print('inputs pillar has been loaded')
    context['conclusion'] = load_conclusion_pillar(subject_ids) # Exception
    print('conclusion pillar has been loaded')

    return context

def data_preparation(subject_ids=None):

    print('Loading discharges...')
    discharges = load_discharges(subject_ids)
    if 'storetime' in discharges.columns:
        discharges['storetime'] = pd.to_datetime(discharges['storetime'])
        discharges = discharges.sort_values(['subject_id', 'storetime'])
    
    print('Discharges were loaded.\nLoading the context...')
    clinical_data_dict = load_clinical_context(subject_ids)
    cases_data = []

    for subject_id, group in discharges.groupby('subject_id'):
        subj_context = {k: df[df['subject_id'] == subject_id].copy() for k, df in clinical_data_dict.items()}
        prev_timestamp = pd.Timestamp.min
        for case in group.itertuples(index=False):
            current_timestamp = case.storetime
            window_cuts = {}
            
            for category, df in subj_context.items():
                if 'timestamp' in df.columns:
                    df['timestamp'] = pd.to_datetime(df['timestamp'])
                    mask = (df['timestamp'] <= current_timestamp) & (df['timestamp'] > prev_timestamp)
                    window_cuts[category] = df[mask]
            
            # context_textual = context_builder_v2(window_cuts)
            context_textual = context_builder_v3(window_cuts)
            cases_data.append({
                'subject_id': subject_id,
                'hadm_id': getattr(case, 'hadm_id', None),
                'context_textual': context_textual,
                'aaaa': window_cuts,
            })

            prev_timestamp = current_timestamp

    return pd.DataFrame(cases_data)

In [7]:
df = data_preparation([10000032]) # , 10000117  [10000032, 10001217, 10001725] ## 10000084, 10000248,

Loading discharges...
Discharges were loaded.
Loading the context...
identity pillar has been loaded
logistics pillar has been loaded
monitoring pillar has been loaded
investigations pillar has been loaded
interventions pillar has been loaded
inputs pillar has been loaded
conclusion pillar has been loaded

/tmp/ipykernel_158592/1949692064.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  monitoring_df = pd.concat([icu_vitals, ward_vitals], axis=0, ignore_index=True)
/tmp/ipykernel_158592/1949692064.py:362: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat([icu_inputs, ward_inputs], axis=0, ignore_index=True)

In [8]:
print(df.iloc[1]['context_textual'])

--- Patient Information ---
Patient is a 52 year old F (WHITE). They were admitted via EMERGENCY ROOM by EW EMER.. Baseline patient data shows: weight 94, height 60, bmi 18.0, blood pressure 110/65.

--- Hospital Course ---

Day 1
The patient initially presented at the Emergency Department (Emergency Department). The patient was formally admitted to Transplant via EMERGENCY ROOM.
Abnormal Lab Findings:
- WBC: 13.0#/hpf
Microbiology & Immunology:
- URINE (URINE CULTURE): MIXED BACTERIAL FLORA ( >= 3 COLONY TYPES), CONSISTENT WITH SKIN AND/OR GENITAL CONTAMINATION
- SWAB (R/O VANCOMYCIN RESISTANT ENTEROCOCCUS): No VRE isolated
Medication Administration History:
- Sodium Chloride 0.9%  Flush dose of 3 mL via IV
- Influenza Vaccine Quadrivalent dose of 0.5 mL via IM
- Heparin dose of 5000 UNIT via SC
- Rifaximin dose of 550 mg via PO/NG
- Albuterol Inhaler dose of 2 PUFF via IH
- Calcium Carbonate dose of 1250 mg via PO/NG
- Furosemide dose of 20 mg via PO/NG
- Acetaminophen dose of 500 mg via PO/NG
- Tiotropium Bromide dose of 1 CAP via IH
- Emtricitabine-Tenofovir (Truvada) dose of 1 TAB via PO
- Lactulose dose of 30 mL via PO/NG
- Raltegravir dose of 400 mg via PO
- Sulfameth/Trimethoprim DS dose of 1 TAB via PO/NG
Major/Billed Procedures:
- nan

Day 2

The patient was discharged HOME by the end of the day.
Abnormal Lab Findings:
- Hematocrit: 35.5%
- Potassium: 5.2mEq/L
- Creatinine: 0.3mg/dL
- Chloride: 92.0mEq/L
- Calcium, Total: 7.8mg/dL
- Asparate Aminotransferase (AST): 158.0IU/L
- Sodium: 126.0mEq/L
- Alkaline Phosphatase: 110.0IU/L
- Alanine Aminotransferase (ALT): 117.0IU/L
- PT: 16.3sec
- INR(PT): 1.5
- Red Blood Cells: 3.6m/uL
- RDW: 15.7%
- Platelet Count: 137.0K/uL
- MCV: 99.0fL
- MCH: 34.5pg
- Albumin: 2.7g/dL
- Urea Nitrogen: 29.0mg/dL
Medication Administration History:
- Furosemide dose of 40 mg via PO/NG
- Albumin 25% (12.5g / 50mL) dose of 37.5 g via IV

--- Conclusions ---
Hospital Course Summary:


Medication Summary:
- Furosemide: 2 administrations
- Sodium Chloride 0.9%  Flush: 1 administrations
- Heparin: 1 administrations
- Rifaximin: 1 administrations
- Albuterol Inhaler: 1 administrations
- Influenza Vaccine Quadrivalent: 1 administrations
- Calcium Carbonate: 1 administrations
- Acetaminophen: 1 administrations
- Tiotropium Bromide: 1 administrations
- Emtricitabine-Tenofovir (Truvada): 1 administrations
- Lactulose: 1 administrations
- Raltegravir: 1 administrations
- Sulfameth/Trimethoprim DS: 1 administrations
- Albumin 25% (12.5g / 50mL): 1 administrations

Abnormal Lab Summary:
- WBC: 1 abnormal readings
- Hematocrit: 1 abnormal readings
- MCH: 1 abnormal readings
- MCV: 1 abnormal readings
- Platelet Count: 1 abnormal readings
- RDW: 1 abnormal readings
- Red Blood Cells: 1 abnormal readings
- INR(PT): 1 abnormal readings
- PT: 1 abnormal readings
- Alanine Aminotransferase (ALT): 1 abnormal readings
- Albumin: 1 abnormal readings
- Alkaline Phosphatase: 1 abnormal readings
- Asparate Aminotransferase (AST): 1 abnormal readings
- Calcium, Total: 1 abnormal readings
- Chloride: 1 abnormal readings
- Creatinine: 1 abnormal readings
- Potassium: 1 abnormal readings
- Sodium: 1 abnormal readings
- Urea Nitrogen: 1 abnormal readings

Primary Diagnosis: ICD-9 07071.
Secondary Conditions: ICD-9 78959, ICD-9 2875, ICD-9 2761, ICD-9 496, ICD-9 5715, ICD-9 V08, ICD-9 3051.

In [9]:
for i in range(len(df)):
    print(df.iloc[i]['context_textual'])

--- Patient Information ---
Patient is a 52 year old F (WHITE). They were admitted via TRANSFER FROM HOSPITAL by URGENT. Baseline patient data shows: weight 94, height 60, bmi 18.0, blood pressure 110/65.

--- Hospital Course ---

Day 1
The patient initially presented at the Emergency Department (Emergency Department). The patient was formally admitted to Transplant via TRANSFER FROM HOSPITAL.
Major/Billed Procedures:
- nan

Day 2

The patient was discharged HOME by the end of the day.
Abnormal Lab Findings:
- Urobilinogen: 4.0mg/dL
- Calcium, Total: 7.8mg/dL
- Creatinine: 0.3mg/dL
- Urea Nitrogen: 25.0mg/dL
- Asparate Aminotransferase (AST): 98.0IU/L
- INR(PT): 1.5
- Alanine Aminotransferase (ALT): 88.0IU/L
- MCH: 33.4pg
- MCV: 99.0fL
- Platelet Count: 71.0K/uL
- Red Blood Cells: 3.8m/uL
- PT: 16.6sec
- nan: 300.0#/uL
- RBC, Ascites: 8800.0#/uL
- Eosinophils: 1.0%
- Mesothelial Cell: 2.0%
- Macrophage: 35.0%
- Lymphocytes: 49.0%
- Polys: 13.0%
Microbiology & Immunology:
- URINE (URINE CULTURE): MIXED BACTERIAL FLORA ( >= 3 COLONY TYPES), CONSISTENT WITH SKIN AND/OR GENITAL CONTAMINATION
- SWAB (R/O VANCOMYCIN RESISTANT ENTEROCOCCUS): No VRE isolated
- PERITONEAL FLUID (GRAM STAIN): 2+   (1-5 per 1000X FIELD):   POLYMORPHONUCLEAR LEUKOCYTES
- PERITONEAL FLUID (FLUID CULTURE): NO GROWTH
- PERITONEAL FLUID (ANAEROBIC CULTURE): NO GROWTH
Medication Administration History:
- Sodium Chloride 0.9%  Flush dose of 3 mL via IV
- Influenza Vaccine Quadrivalent dose of 0.5 mL via IM
- Heparin dose of 5000 UNIT via SC
- Furosemide dose of 20 mg via PO/NG
- Potassium Chloride dose of 40 mEq via PO
- Raltegravir dose of 400 mg via PO
- Acetaminophen dose of 500 mg via PO/NG
- Albuterol Inhaler dose of 2 PUFF via IH
- Emtricitabine-Tenofovir (Truvada) dose of 1 TAB via PO
- Spironolactone dose of 50 mg via PO/NG
- Nicotine Patch dose of 14 mg via TD
- Ipratropium Bromide Neb dose of 1 NEB via IH

Day 3
Medication Administration History:
- Furosemide dose of 40 mg via PO/NG
- Spironolactone dose of 50 mg via PO/NG

--- Conclusions ---
Hospital Course Summary:


Medication Summary:
- Furosemide: 2 administrations
- Spironolactone: 2 administrations
- Influenza Vaccine Quadrivalent: 1 administrations
- Sodium Chloride 0.9%  Flush: 1 administrations
- Heparin: 1 administrations
- Potassium Chloride: 1 administrations
- Acetaminophen: 1 administrations
- Raltegravir: 1 administrations
- Albuterol Inhaler: 1 administrations
- Emtricitabine-Tenofovir (Truvada): 1 administrations
- Nicotine Patch: 1 administrations
- Ipratropium Bromide Neb: 1 administrations

Abnormal Lab Summary:
- Urobilinogen: 1 abnormal readings
- MCH: 1 abnormal readings
- MCV: 1 abnormal readings
- Platelet Count: 1 abnormal readings
- Red Blood Cells: 1 abnormal readings
- INR(PT): 1 abnormal readings
- PT: 1 abnormal readings
- Alanine Aminotransferase (ALT): 1 abnormal readings
- Asparate Aminotransferase (AST): 1 abnormal readings
- Calcium, Total: 1 abnormal readings
- Creatinine: 1 abnormal readings
- Urea Nitrogen: 1 abnormal readings
- Eosinophils: 1 abnormal readings
- Lymphocytes: 1 abnormal readings
- Macrophage: 1 abnormal readings
- Mesothelial Cell: 1 abnormal readings
- Polys: 1 abnormal readings
- RBC, Ascites: 1 abnormal readings

Primary Diagnosis: ICD-9 5723.
Secondary Conditions: ICD-9 78959, ICD-9 5715, ICD-9 07070, ICD-9 496, ICD-9 29680, ICD-9 30981, ICD-9 V1582.
--- Patient Information ---
Patient is a 52 year old F (WHITE). They were admitted via EMERGENCY ROOM by EW EMER.. Baseline patient data shows: weight 94, height 60, bmi 18.0, blood pressure 110/65.

--- Hospital Course ---

Day 1
The patient initially presented at the Emergency Department (Emergency Department). The patient was formally admitted to Transplant via EMERGENCY ROOM.
Abnormal Lab Findings:
- WBC: 13.0#/hpf
Microbiology & Immunology:
- URINE (URINE CULTURE): MIXED BACTERIAL FLORA ( >= 3 COLONY TYPES), CONSISTENT WITH SKIN AND/OR GENITAL CONTAMINATION
- SWAB (R/O VANCOMYCIN RESISTANT ENTEROCOCCUS): No VRE isolated
Medication Administration History:
- Sodium Chloride 0.9%  Flush dose of 3 mL via IV
- Influenza Vaccine Quadrivalent dose of 0.5 mL via IM
- Heparin dose of 5000 UNIT via SC
- Rifaximin dose of 550 mg via PO/NG
- Albuterol Inhaler dose of 2 PUFF via IH
- Calcium Carbonate dose of 1250 mg via PO/NG
- Furosemide dose of 20 mg via PO/NG
- Acetaminophen dose of 500 mg via PO/NG
- Tiotropium Bromide dose of 1 CAP via IH
- Emtricitabine-Tenofovir (Truvada) dose of 1 TAB via PO
- Lactulose dose of 30 mL via PO/NG
- Raltegravir dose of 400 mg via PO
- Sulfameth/Trimethoprim DS dose of 1 TAB via PO/NG
Major/Billed Procedures:
- nan

Day 2

The patient was discharged HOME by the end of the day.
Abnormal Lab Findings:
- Hematocrit: 35.5%
- Potassium: 5.2mEq/L
- Creatinine: 0.3mg/dL
- Chloride: 92.0mEq/L
- Calcium, Total: 7.8mg/dL
- Asparate Aminotransferase (AST): 158.0IU/L
- Sodium: 126.0mEq/L
- Alkaline Phosphatase: 110.0IU/L
- Alanine Aminotransferase (ALT): 117.0IU/L
- PT: 16.3sec
- INR(PT): 1.5
- Red Blood Cells: 3.6m/uL
- RDW: 15.7%
- Platelet Count: 137.0K/uL
- MCV: 99.0fL
- MCH: 34.5pg
- Albumin: 2.7g/dL
- Urea Nitrogen: 29.0mg/dL
Medication Administration History:
- Furosemide dose of 40 mg via PO/NG
- Albumin 25% (12.5g / 50mL) dose of 37.5 g via IV

--- Conclusions ---
Hospital Course Summary:


Medication Summary:
- Furosemide: 2 administrations
- Sodium Chloride 0.9%  Flush: 1 administrations
- Heparin: 1 administrations
- Rifaximin: 1 administrations
- Albuterol Inhaler: 1 administrations
- Influenza Vaccine Quadrivalent: 1 administrations
- Calcium Carbonate: 1 administrations
- Acetaminophen: 1 administrations
- Tiotropium Bromide: 1 administrations
- Emtricitabine-Tenofovir (Truvada): 1 administrations
- Lactulose: 1 administrations
- Raltegravir: 1 administrations
- Sulfameth/Trimethoprim DS: 1 administrations
- Albumin 25% (12.5g / 50mL): 1 administrations

Abnormal Lab Summary:
- WBC: 1 abnormal readings
- Hematocrit: 1 abnormal readings
- MCH: 1 abnormal readings
- MCV: 1 abnormal readings
- Platelet Count: 1 abnormal readings
- RDW: 1 abnormal readings
- Red Blood Cells: 1 abnormal readings
- INR(PT): 1 abnormal readings
- PT: 1 abnormal readings
- Alanine Aminotransferase (ALT): 1 abnormal readings
- Albumin: 1 abnormal readings
- Alkaline Phosphatase: 1 abnormal readings
- Asparate Aminotransferase (AST): 1 abnormal readings
- Calcium, Total: 1 abnormal readings
- Chloride: 1 abnormal readings
- Creatinine: 1 abnormal readings
- Potassium: 1 abnormal readings
- Sodium: 1 abnormal readings
- Urea Nitrogen: 1 abnormal readings

Primary Diagnosis: ICD-9 07071.
Secondary Conditions: ICD-9 78959, ICD-9 2875, ICD-9 2761, ICD-9 496, ICD-9 5715, ICD-9 V08, ICD-9 3051.
--- Patient Information ---
Patient is a 52 year old F (WHITE). They were admitted via EMERGENCY ROOM by EW EMER.. Baseline patient data shows: weight 94, height 60, bmi 18.0, blood pressure 110/65.

--- Hospital Course ---

Day 1
The patient initially presented at the Emergency Department (Emergency Department).

Day 2
The patient initially presented at the Emergency Department (Emergency Department). The patient was formally admitted to Medical Intensive Care Unit (MICU) via EMERGENCY ROOM.
Internal movements within the hospital included:
 - Moved to Transplant for 20 hours.
Vital Signs and Observations:
- Heart Rhythm: No value recorded
- Temperature Site: No value recorded
- Ectopy Type 1: No value recorded
- Temperature Fahrenheit: 98.7°F
- Non Invasive Blood Pressure systolic: 84.0mmHg
- Non Invasive Blood Pressure diastolic: 48.0mmHg
- Non Invasive Blood Pressure mean: 56.0mmHg
- Heart Rate: 91.0bpm
- Respiratory Rate: 24.0insp/min
- O2 saturation pulseoxymetry: 98.0%
- Pain Cause: No value recorded
- Pain Present: No value recorded
- Pain Location: No value recorded
- Pain Cause: No value recorded
- Pain Assessment Method: No value recorded
- Pain Level: 7.0
- Pain Level Acceptable: No value recorded
- Untoward Effect: No value recorded
- Pain Type: No value recorded
- Non-Invasive Blood Pressure Alarm - Low: 80.0mmHg
- O2 Saturation Pulseoxymetry Alarm - High: 100.0%
- Heart Rate Alarm - Low: 60.0bpm
- Non-Invasive Blood Pressure Alarm - High: 160.0mmHg
- Heart rate Alarm - High: 120.0bpm
- Resp Alarm - High: 35.0insp/min
- Resp Alarm - Low: 8.0insp/min
- Parameters Checked: 1.0
- Alarms On: 1.0
- O2 Saturation Pulseoxymetry Alarm - Low: 92.0%
- O2 Flow: 2.0L/min
- Family Communication: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Barrier: No value recorded
- Family Communication: No value recorded
- Family Communication: No value recorded
- Support Systems: No value recorded
- Education Barrier: No value recorded
- Education Method: No value recorded
- Education Learner: No value recorded
- Position: No value recorded
- Activity Tolerance: No value recorded
- Education Topic: No value recorded
- Turn: No value recorded
- Head of Bed: No value recorded
- Education Response: No value recorded
- Activity: No value recorded
- Therapeutic Bed: No value recorded
- Pressure Reducing Device: No value recorded
- Anti Embolic Device: No value recorded
- Code Status: No value recorded
- Service: No value recorded
- Heart Rhythm: No value recorded
- Non Invasive Blood Pressure diastolic: 59.0mmHg
- Heart Rate: 93.0bpm
- Non Invasive Blood Pressure systolic: 95.0mmHg
- O2 saturation pulseoxymetry: 97.0%
- Ectopy Type 1: No value recorded
- Respiratory Rate: 21.0insp/min
- Non Invasive Blood Pressure mean: 67.0mmHg
- Support Systems: No value recorded
- Family Communication: No value recorded
- Family Communication: No value recorded
- Family Communication: No value recorded
- Code Status: No value recorded
- Service: No value recorded
- GCS - Eye Opening: 4.0
- GCS - Motor Response: 6.0
- GCS - Verbal Response: 4.0
- Urine Source: No value recorded
- Cough Effort: No value recorded
- Skin Temperature: No value recorded
- Respiratory Pattern: No value recorded
- Braden Sensory Perception: 3.0
- Respiratory Effort: No value recorded
- Edema Location: No value recorded
- Braden Friction/Shear: 2.0
- Braden Moisture: 3.0
- Skin Integrity: No value recorded
- Skin Condition: No value recorded
- Braden Activity: 3.0
- Braden Nutrition: 2.0
- Braden Mobility: 2.0
- Skin Color: No value recorded
- Nares R: No value recorded
- Dorsal PedPulse R: No value recorded
- Dorsal PedPulse L: No value recorded
- RLE Color: No value recorded
- LUE Color: No value recorded
- LLE Color: No value recorded
- Oral Cavity: No value recorded
- RUE Color: No value recorded
- Diet Type: No value recorded
- Abdominal Assessment: No value recorded
- Bowel Sounds: No value recorded
- RUE Temp: No value recorded
- RLE Temp: No value recorded
- LLE Temp: No value recorded
- Nares L: No value recorded
- LUE Temp: No value recorded
- Heart Rhythm: No value recorded
- Head of Bed: No value recorded
- Turn: No value recorded
- Activity: No value recorded
- Position: No value recorded
- Heart Rate: 94.0bpm
- Activity Tolerance: No value recorded
- Respiratory Rate: 23.0insp/min
- Non Invasive Blood Pressure diastolic: 56.0mmHg
- Non Invasive Blood Pressure mean: 64.0mmHg
- O2 saturation pulseoxymetry: 97.0%
- Ectopy Type 1: No value recorded
- Anti Embolic Device: No value recorded
- Non Invasive Blood Pressure systolic: 88.0mmHg
- RUL Lung Sounds: No value recorded
- Radial Pulse L: No value recorded
- LUL Lung Sounds: No value recorded
- RUL Lung Sounds: No value recorded
- Radial Pulse R: No value recorded
- Stool Consistency: No value recorded
- Stool Color: No value recorded
- Heart Rate: 105.0bpm
- Heart Rhythm: No value recorded
- Respiratory Rate: 21.0insp/min
- O2 saturation pulseoxymetry: 94.0%
- Ectopy Type 1: No value recorded
- Non Invasive Blood Pressure mean: 64.0mmHg
- Non Invasive Blood Pressure systolic: 91.0mmHg
- Non Invasive Blood Pressure diastolic: 55.0mmHg
- Head of Bed: No value recorded
- Turn: No value recorded
- Activity: No value recorded
- Activity Tolerance: No value recorded
- Position: No value recorded
- Respiratory Rate: 20.0insp/min
- Heart Rhythm: No value recorded
- Non Invasive Blood Pressure systolic: 95.0mmHg
- Non Invasive Blood Pressure diastolic: 58.0mmHg
- Non Invasive Blood Pressure mean: 67.0mmHg
- O2 saturation pulseoxymetry: 95.0%
- Temperature Site: No value recorded
- Ectopy Type 1: No value recorded
- Temperature Fahrenheit: 98.7°F
- Support Systems: No value recorded
- Family Communication: No value recorded
- Family Communication: No value recorded
- Heart Rate: 97.0bpm
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Barrier: No value recorded
- Education Method: No value recorded
- Education Response: No value recorded
- Education Learner: No value recorded
- Heart Rate: 100.0bpm
- Heart Rhythm: No value recorded
- Non Invasive Blood Pressure systolic: 86.0mmHg
- Family Communication: No value recorded
- Non Invasive Blood Pressure diastolic: 53.0mmHg
- O2 saturation pulseoxymetry: 95.0%
- Non Invasive Blood Pressure mean: 60.0mmHg
- Ectopy Type 1: No value recorded
- O2 Flow: 2.0L/min
- Support Systems: No value recorded
- Respiratory Rate: 21.0insp/min
- GCS - Verbal Response: 5.0
- GCS - Motor Response: 6.0
- GCS - Eye Opening: 4.0
- Pain Present: No value recorded
- Pain Type: No value recorded
- Pain Location: No value recorded
- Pain Location: No value recorded
- Pain Location: No value recorded
- Pain Cause: No value recorded
- Pain Level: 8.0
- Pain Management: No value recorded
- Pain Management: No value recorded
- Pain Level Acceptable: No value recorded
- Pain Assessment Method: No value recorded
- Untoward Effect: No value recorded
- Education Topic: No value recorded
- Education Topic: No value recorded
- Education Learner: No value recorded
- Education Method: No value recorded
- Education Response: No value recorded
- Education Barrier: No value recorded
- Head of Bed: No value recorded
- Turn: No value recorded
- Activity: No value recorded
- Activity Tolerance: No value recorded
- Therapeutic Bed: No value recorded
- Anti Embolic Device: No value recorded
- Position: No value recorded
- Non Invasive Blood Pressure mean: 56.0mmHg
- Heart Rate: 97.0bpm
- Non Invasive Blood Pressure systolic: 93.0mmHg
- Non Invasive Blood Pressure diastolic: 41.0mmHg
- O2 saturation pulseoxymetry: 98.0%
- Heart Rhythm: No value recorded
- Ectopy Type 1: No value recorded
- Respiratory Rate: 16.0insp/min
- Ectopy Type 1: No value recorded
- O2 saturation pulseoxymetry: 99.0%
- Non Invasive Blood Pressure systolic: 90.0mmHg
- Non Invasive Blood Pressure mean: 64.0mmHg
- Non Invasive Blood Pressure diastolic: 57.0mmHg
- Temperature Site: No value recorded
- Heart Rhythm: No value recorded
- Heart Rate: 100.0bpm
- Temperature Fahrenheit: 99.5°F
- GCS - Eye Opening: 4.0
- Alarms On: 1.0
- Respiratory Rate: 19.0insp/min
- GCS - Motor Response: 6.0
- O2 Flow: 2.0L/min
- GCS - Verbal Response: 5.0
- Dorsal PedPulse L: No value recorded
- Parameters Checked: 1.0
- Dorsal PedPulse R: No value recorded
- Respiratory Effort: No value recorded
- LUL Lung Sounds: No value recorded
- RUL Lung Sounds: No value recorded
- Respiratory Pattern: No value recorded
- Cough Effort: No value recorded
- Ectopy Type 1: No value recorded
- Activity: No value recorded
- Heart Rate: 94.0bpm
- Heart Rhythm: No value recorded
- Respiratory Rate: 22.0insp/min
- O2 saturation pulseoxymetry: 95.0%
- Head of Bed: No value recorded
- Activity Tolerance: No value recorded
- Anti Embolic Device: No value recorded
- Position: No value recorded
- Support Systems: No value recorded
- Family Communication: No value recorded
- Family Communication: No value recorded
- Therapeutic Bed: No value recorded
- Turn: No value recorded
- Non Invasive Blood Pressure systolic: 82.0mmHg
- Non Invasive Blood Pressure diastolic: 59.0mmHg
- Non Invasive Blood Pressure mean: 63.0mmHg
- Education Response: No value recorded
- Education Learner: No value recorded
- Pain Type: No value recorded
- Education Barrier: No value recorded
- Education Method: No value recorded
- Pain Present: No value recorded
- Education Topic: No value recorded
- Pain Location: No value recorded
- Pain Management: No value recorded
- Pain Management: No value recorded
- Untoward Effect: No value recorded
- Pain Assessment Method: No value recorded
- Pain Cause: No value recorded
- Pain Level Acceptable: No value recorded
- Skin Temperature: No value recorded
- Oral Cavity: No value recorded
- Nares R: No value recorded
- Abdominal Assessment: No value recorded
- Bowel Sounds: No value recorded
- Urine Source: No value recorded
- Nares L: No value recorded
- Skin Integrity: No value recorded
- Braden Nutrition: 2.0
- Diet Type: No value recorded
- Edema Location: No value recorded
- Braden Sensory Perception: 3.0
- Braden Moisture: 3.0
- Braden Activity: 2.0
- Braden Mobility: 3.0
- Braden Friction/Shear: 2.0
- Skin Condition: No value recorded
- Edema Amount: No value recorded
- Skin Color: No value recorded
- Chloride (serum): 102.0mEq/L
- Sodium (serum): 132.0mEq/L
- Creatinine (serum): 0.5mg/dL
- Magnesium: 2.3mg/dL
- Glucose (serum): 115.0mg/dL
- Heart rate Alarm - High: 120.0bpm
- Heart Rate Alarm - Low: 60.0bpm
- Non-Invasive Blood Pressure Alarm - High: 160.0mmHg
- Non-Invasive Blood Pressure Alarm - Low: 85.0mmHg
- O2 Saturation Pulseoxymetry Alarm - High: 100.0%
- O2 Saturation Pulseoxymetry Alarm - Low: 92.0%
- Resp Alarm - High: 35.0insp/min
- Resp Alarm - Low: 8.0insp/min
- Non Invasive Blood Pressure mean: 62.0mmHg
- Respiratory Rate: 20.0insp/min
- Heart Rate: 94.0bpm
- Non Invasive Blood Pressure systolic: 85.0mmHg
- Non Invasive Blood Pressure diastolic: 55.0mmHg
- O2 saturation pulseoxymetry: 95.0%
Abnormal Lab Findings:
- Bicarbonate: 21.0mEq/L
- Glucose: 115.0mg/dL
- Phosphate: 2.4mg/dL
- Sodium: 132.0mEq/L
- Urea Nitrogen: 33.0mg/dL
Microbiology & Immunology:
- MRSA SCREEN (MRSA SCREEN): No MRSA isolated
Medication Administration History:
- Bisacodyl dose of 10 mg via PR
- Bisacodyl dose of 10 mg via PO
- Senna dose of 8.6 mg via PO
- Docusate Sodium (Liquid) dose of 100 mg via PO
- Influenza Vaccine Quadrivalent dose of 0.5 mL via IM
- Heparin dose of 5000 UNIT via SC
- Tiotropium Bromide dose of 1 CAP via IH
- Emtricitabine-Tenofovir (Truvada) dose of 1 TAB via PO
- Albumin 25% (12.5g / 50mL) dose of 25 g via IV
- Lactulose dose of 30 mL via PO/NG
- Albuterol 0.083% Neb Soln dose of 1 NEB via IH
- Fluticasone Propionate 110mcg dose of 1 PUFF via IH
- Raltegravir dose of 400 mg via PO
- Calcium Carbonate dose of 500 mg via PO/NG
- Albumin 25% 49.999998807907104 mL at 100.0 mL/hour via IV
- nan dose of 200.0 mL via IV
- Albumin 25% 49.999998807907104 mL at 100.0 mL/hour via IV
- nan dose of 100.0 mL via IV
- Rifaximin dose of 550 mg via PO/NG
- nan dose of 100.0 mL via IV
- TraMADOL (Ultram) dose of 25 mg via PO
ICU Bedside Interventions:
- 20 Gauge
- 18 Gauge
- nan

Day 3

Internal movements within the hospital included:
 - Moved to Transplant for 22 hours.
Abnormal Lab Findings:
- INR(PT): 1.8
- Red Blood Cells: 3.4m/uL
- RDW: 15.8%
- Platelet Count: 94.0K/uL
- MCV: 102.0fL
- MCH: 34.9pg
- Hemoglobin: 11.9g/dL
- Hematocrit: 34.8%
- Urea Nitrogen: 28.0mg/dL
- Sodium: 130.0mEq/L
- PT: 19.5sec
- Glucose: 107.0mg/dL
- Bilirubin, Total: 2.7mg/dL
- Asparate Aminotransferase (AST): 187.0IU/L
- Alanine Aminotransferase (ALT): 114.0IU/L
- Phosphate: 2.2mg/dL
Microbiology & Immunology:
- SWAB (R/O VANCOMYCIN RESISTANT ENTEROCOCCUS): No VRE isolated
Medication Administration History:
- Sodium Chloride 0.9%  Flush dose of 3 mL via IV
- TraMADOL (Ultram) dose of 25-50 mg via PO

In [10]:
df.iloc[0]['aaaa']['inputs']

,subject_id,hadm_id,timestamp,label,amount,amountuom,rate,rateuom,route,input_type
9,10000032,22595853,2180-05-07 00:00:00,Sodium Chloride 0.9% Flush,3,mL,NaN,NaN,IV,WARD_PRESCRIPTION
13,10000032,22595853,2180-05-07 00:00:00,Influenza Vaccine Quadrivalent,0.5,mL,NaN,NaN,IM,WARD_PRESCRIPTION
17,10000032,22595853,2180-05-07 00:00:00,Heparin,5000,UNIT,NaN,NaN,SC,WARD_PRESCRIPTION
7,10000032,22595853,2180-05-07 01:00:00,Furosemide,20,mg,NaN,NaN,PO/NG,WARD_PRESCRIPTION
8,10000032,22595853,2180-05-07 01:00:00,Potassium Chloride,40,mEq,NaN,NaN,PO,WARD_PRESCRIPTION
10,10000032,22595853,2180-05-07 01:00:00,Raltegravir,400,mg,NaN,NaN,PO,WARD_PRESCRIPTION
12,10000032,22595853,2180-05-07 01:00:00,Acetaminophen,500,mg,NaN,NaN,PO/NG,WARD_PRESCRIPTION
14,10000032,22595853,2180-05-07 01:00:00,Albuterol Inhaler,2,PUFF,NaN,NaN,IH,WARD_PRESCRIPTION
15,10000032,22595853,2180-05-07 01:00:00,Emtricitabine-Tenofovir (Truvada),1,TAB,NaN,NaN,PO,WARD_PRESCRIPTION
16,10000032,22595853,2180-05-07 01:00:00,Spironolactone,50,mg,NaN,NaN,PO/NG,WARD_PRESCRIPTION
18,10000032,22595853,2180-05-07 01:00:00,Nicotine Patch,14,mg,NaN,NaN,TD,WARD_PRESCRIPTION
6,10000032,22595853,2180-05-07 02:00:00,Ipratropium Bromide Neb,1,NEB,NaN,NaN,IH,WARD_PRESCRIPTION
5,10000032,22595853,2180-05-08 08:00:00,Furosemide,40,mg,NaN,NaN,PO/NG,WARD_PRESCRIPTION
11,10000032,22595853,2180-05-08 08:00:00,Spironolactone,50,mg,NaN,NaN,PO/NG,WARD_PRESCRIPTION

In [11]:
df.iloc[2]['aaaa']['conclusion']

,subject_id,hadm_id,timestamp,diagnosis_label,seq_num,icd_code,icd_version
26,10000032,29079034,2180-07-25 17:55:00,ICD Code 45829,1,45829,9
27,10000032,29079034,2180-07-25 17:55:00,ICD Code 07044,2,07044,9
28,10000032,29079034,2180-07-25 17:55:00,ICD Code 7994,3,7994,9
29,10000032,29079034,2180-07-25 17:55:00,ICD Code 2761,4,2761,9
30,10000032,29079034,2180-07-25 17:55:00,ICD Code 78959,5,78959,9
31,10000032,29079034,2180-07-25 17:55:00,ICD Code 2767,6,2767,9
32,10000032,29079034,2180-07-25 17:55:00,ICD Code 3051,7,3051,9
33,10000032,29079034,2180-07-25 17:55:00,ICD Code V08,8,V08,9
34,10000032,29079034,2180-07-25 17:55:00,ICD Code V4986,9,V4986,9
35,10000032,29079034,2180-07-25 17:55:00,ICD Code V462,10,V462,9
36,10000032,29079034,2180-07-25 17:55:00,ICD Code 496,11,496,9
37,10000032,29079034,2180-07-25 17:55:00,ICD Code 29680,12,29680,9
38,10000032,29079034,2180-07-25 17:55:00,ICD Code 5715,13,5715,9

In [12]:
if 'logistics' in window_cuts and not window_cuts['logistics'].empty:
        log = window_cuts['logistics'].sort_values('timestamp')
        units = " -> ".join(log['careunit'].unique())
        paragraphs.append(f"Clinical course involved the following units: {units}.")

NameError: name 'window_cuts' is not defined